In [1]:
import pandas as pd

In [2]:
def show(df, metric, plugin_metric, plugin_models, rscore_models):
    plugin_cols = [f'{metric}_{pm}_{plugin_metric}' for pm in plugin_models]
    rscore_cols = [f'{metric}_rs_{rs_bm}' for rs_bm in rscore_models]
    cols = ['name', f'{metric}_mse', f'{metric}_r2', f'{metric}_mixed'] + plugin_cols + rscore_cols + [f'{metric}_test']
    return df[cols]

## IHDP

In [3]:
plugin_meta_models = ['sl', 'tl']
plugin_base_models = ['dt', 'lgbm', 'cb']
plugin_models = [f'{pmm}_{pbm}' for pmm in plugin_meta_models for pbm in plugin_base_models]
rscore_base_models = ['dt', 'lgbm', 'cb']

ds = 'ihdp'
df_all = pd.read_csv(f'./tables/{ds}_compare_metrics_meta.csv')
avg_metric = 'ate'
ite_metric = 'pehe'

In [4]:
df = show(df_all, avg_metric, 'pehe', plugin_models, rscore_base_models)
df

,name,ate_mse,ate_r2,ate_mixed,ate_sl_dt_pehe,ate_sl_lgbm_pehe,ate_sl_cb_pehe,ate_tl_dt_pehe,ate_tl_lgbm_pehe,ate_tl_cb_pehe,ate_rs_dt,ate_rs_lgbm,ate_rs_cb,ate_test
0,sl,0.246 +/- 0.294,0.184 +/- 0.155,-,1.692 +/- 3.794,4.791 +/- 2.711,1.662 +/- 1.725,0.146 +/- 0.115,0.303 +/- 0.353,0.314 +/- 0.469,1.050 +/- 0.495,0.318 +/- 0.185,0.596 +/- 0.247,0.001 +/- 0.003
1,tl,0.168 +/- 0.293,0.180 +/- 0.288,-,1.725 +/- 3.780,4.791 +/- 2.711,1.600 +/- 1.426,0.395 +/- 0.503,0.230 +/- 0.389,0.233 +/- 0.382,0.968 +/- 0.393,0.202 +/- 0.203,0.335 +/- 0.248,0.000 +/- 0.000
2,ipsws,0.131 +/- 0.101,0.261 +/- 0.279,-,1.668 +/- 3.803,4.791 +/- 2.711,1.350 +/- 1.735,0.315 +/- 0.528,0.388 +/- 0.537,0.352 +/- 0.549,0.935 +/- 0.598,0.315 +/- 0.258,0.528 +/- 0.172,0.001 +/- 0.001
3,drs,-,-,0.211 +/- 0.236,1.664 +/- 3.805,4.791 +/- 2.711,0.854 +/- 1.234,0.360 +/- 0.492,0.228 +/- 0.381,0.186 +/- 0.307,0.835 +/- 1.600,0.533 +/- 1.051,0.551 +/- 1.051,0.002 +/- 0.002
4,dmls,-,-,0.438 +/- 0.407,1.274 +/- 2.499,2.800 +/- 1.972,1.861 +/- 1.517,0.479 +/- 0.842,0.409 +/- 0.377,0.330 +/- 0.376,1.625 +/- 1.775,0.508 +/- 0.542,0.654 +/- 0.459,0.007 +/- 0.010
5,xl,-,-,-,1.650 +/- 3.810,4.791 +/- 2.711,1.044 +/- 1.000,0.377 +/- 0.551,0.418 +/- 0.640,0.370 +/- 0.586,0.836 +/- 0.718,0.270 +/- 0.404,0.288 +/- 0.198,0.009 +/- 0.020
6,cf,-,-,-,0.293 +/- 0.585,0.299 +/- 0.583,0.292 +/- 0.582,0.227 +/- 0.385,0.273 +/- 0.521,0.228 +/- 0.386,0.239 +/- 0.389,0.240 +/- 0.388,0.240 +/- 0.388,0.198 +/- 0.392
7,sl_mlp,0.486 +/- 0.385,0.486 +/- 0.385,-,0.762 +/- 1.178,2.664 +/- 0.941,1.529 +/- 1.690,1.917 +/- 4.749,1.921 +/- 4.748,1.919 +/- 4.749,2.416 +/- 4.592,0.342 +/- 0.201,0.672 +/- 0.431,0.104 +/- 0.113
8,tl_mlp,0.221 +/- 0.229,0.198 +/- 0.143,-,0.306 +/- 0.220,0.459 +/- 0.276,0.481 +/- 0.216,0.218 +/- 0.167,0.285 +/- 0.143,0.289 +/- 0.204,0.471 +/- 0.255,0.507 +/- 0.624,0.396 +/- 0.343,0.000 +/- 0.000

In [5]:
df[['name', f'{avg_metric}_mse', f'{avg_metric}_r2', f'{avg_metric}_mixed', f'{avg_metric}_test']]

     name          ate_mse           ate_r2        ate_mixed         ate_test
0      sl  0.246 +/- 0.294  0.184 +/- 0.155                -  0.001 +/- 0.003
1      tl  0.168 +/- 0.293  0.180 +/- 0.288                -  0.000 +/- 0.000
2   ipsws  0.131 +/- 0.101  0.261 +/- 0.279                -  0.001 +/- 0.001
3     drs                -                -  0.211 +/- 0.236  0.002 +/- 0.002
4    dmls                -                -  0.438 +/- 0.407  0.007 +/- 0.010
5      xl                -                -                -  0.009 +/- 0.020
6      cf                -                -                -  0.198 +/- 0.392
7  sl_mlp  0.486 +/- 0.385  0.486 +/- 0.385                -  0.104 +/- 0.113
8  tl_mlp  0.221 +/- 0.229  0.198 +/- 0.143                -  0.000 +/- 0.000

In [9]:
df = show(df_all, ite_metric, 'pehe', plugin_models, rscore_base_models)
df

,name,pehe_mse,pehe_r2,pehe_mixed,pehe_sl_dt_pehe,pehe_sl_lgbm_pehe,pehe_sl_cb_pehe,pehe_tl_dt_pehe,pehe_tl_lgbm_pehe,pehe_tl_cb_pehe,pehe_rs_dt,pehe_rs_lgbm,pehe_rs_cb,pehe_test
0,sl,1.373 +/- 1.836,1.390 +/- 1.932,-,4.257 +/- 7.929,6.998 +/- 6.783,4.091 +/- 5.800,2.334 +/- 3.995,2.643 +/- 3.800,2.347 +/- 3.569,2.190 +/- 2.068,1.548 +/- 2.092,1.609 +/- 1.725,1.205 +/- 1.683
1,tl,0.701 +/- 0.607,0.724 +/- 0.596,-,4.150 +/- 7.970,6.998 +/- 6.783,4.384 +/- 6.081,2.689 +/- 4.397,2.001 +/- 2.914,2.070 +/- 3.232,2.176 +/- 2.045,1.129 +/- 1.136,1.502 +/- 1.712,0.621 +/- 0.601
2,ipsws,1.552 +/- 2.179,2.117 +/- 2.796,-,4.233 +/- 7.936,6.998 +/- 6.783,3.816 +/- 5.918,2.650 +/- 4.148,2.697 +/- 3.905,2.461 +/- 3.770,2.129 +/- 2.119,1.396 +/- 1.827,1.654 +/- 1.953,1.204 +/- 1.680
3,drs,-,-,1.470 +/- 1.873,4.203 +/- 7.950,6.998 +/- 6.783,3.366 +/- 5.050,2.350 +/- 3.773,2.294 +/- 3.227,2.183 +/- 3.184,2.527 +/- 4.042,1.658 +/- 2.380,1.669 +/- 2.365,1.275 +/- 1.744
4,dmls,-,-,1.905 +/- 2.477,2.885 +/- 4.466,4.210 +/- 3.904,3.393 +/- 3.841,2.170 +/- 3.195,2.175 +/- 2.821,2.124 +/- 2.831,3.069 +/- 3.744,2.005 +/- 2.640,2.325 +/- 2.667,1.679 +/- 2.489
5,xl,-,-,-,4.210 +/- 7.947,6.998 +/- 6.783,3.428 +/- 5.112,2.680 +/- 4.152,2.200 +/- 3.043,2.261 +/- 3.354,2.592 +/- 3.251,1.276 +/- 1.344,1.287 +/- 1.218,1.067 +/- 1.226
6,cf,-,-,-,2.903 +/- 4.661,2.948 +/- 4.650,2.880 +/- 4.673,2.594 +/- 4.296,2.545 +/- 3.783,2.331 +/- 3.581,2.300 +/- 3.554,2.295 +/- 3.556,2.297 +/- 3.555,2.290 +/- 3.559
7,sl_mlp,1.064 +/- 0.637,1.064 +/- 0.637,-,3.530 +/- 6.062,5.254 +/- 5.333,3.733 +/- 5.152,3.377 +/- 6.626,3.493 +/- 6.620,3.383 +/- 6.624,3.703 +/- 6.482,1.232 +/- 0.831,1.345 +/- 0.945,0.925 +/- 0.673
8,tl_mlp,0.894 +/- 0.549,0.868 +/- 0.525,-,2.141 +/- 2.989,2.365 +/- 2.875,2.208 +/- 2.963,1.982 +/- 2.786,2.081 +/- 2.534,2.114 +/- 2.790,1.885 +/- 2.209,1.399 +/- 1.488,1.314 +/- 1.401,0.641 +/- 0.570

In [13]:
df[['name_uc', f'{ite_metric}_mse', f'{ite_metric}_r2', f'{ite_metric}_mixed', f'{ite_metric}_test']]

  name_uc         pehe_mse          pehe_r2       pehe_mixed        pehe_test
0      SL  1.373 +/- 1.836  1.390 +/- 1.932                -  1.205 +/- 1.683
1      TL  0.701 +/- 0.607  0.724 +/- 0.596                -  0.621 +/- 0.601
2   IPSWS  1.552 +/- 2.179  2.117 +/- 2.796                -  1.204 +/- 1.680
3     DRS                -                -  1.470 +/- 1.873  1.275 +/- 1.744
4    DMLS                -                -  1.905 +/- 2.477  1.679 +/- 2.489
5      XL                -                -                -  1.067 +/- 1.226
6      CF                -                -                -  2.290 +/- 3.559
7  SL-MLP  1.064 +/- 0.637  1.064 +/- 0.637                -  0.925 +/- 0.673
8  TL-MLP  0.894 +/- 0.549  0.868 +/- 0.525                -  0.641 +/- 0.570

In [12]:
df['name_uc'] = df['name'].apply(lambda x: x.upper().replace('_', '-'))

<ipython-input-12-7835baa63677>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name_uc'] = df['name'].apply(lambda x: x.upper().replace('_', '-'))

## JOBS

In [16]:
plugin_meta_models = ['sl', 'tl']
plugin_base_models = ['dt', 'lgbm']
plugin_models = [f'{pmm}_{pbm}' for pmm in plugin_meta_models for pbm in plugin_base_models]
rscore_base_models = ['dt', 'lgbm', 'cb']

ds = 'jobs'
df_all = pd.read_csv(f'./tables/{ds}_compare_metrics_meta.csv')
avg_metric = 'att'
ite_metric = 'policy'

In [17]:
df = show(df_all, avg_metric, 'pehe', plugin_models, rscore_base_models)
df

,name,att_mse,att_r2,att_mixed,att_sl_dt_pehe,att_sl_lgbm_pehe,att_tl_dt_pehe,att_tl_lgbm_pehe,att_rs_dt,att_rs_lgbm,att_rs_cb,att_test
0,sl,0.066 +/- 0.060,0.076 +/- 0.061,-,0.083 +/- 0.079,0.083 +/- 0.079,0.063 +/- 0.069,0.075 +/- 0.070,0.079 +/- 0.071,0.076 +/- 0.070,0.074 +/- 0.068,0.003 +/- 0.004
1,tl,0.074 +/- 0.069,0.077 +/- 0.067,-,0.138 +/- 0.090,0.137 +/- 0.092,0.070 +/- 0.061,0.071 +/- 0.065,0.070 +/- 0.075,0.081 +/- 0.074,0.074 +/- 0.056,0.000 +/- 0.000
2,ipsws,0.077 +/- 0.075,0.080 +/- 0.073,-,0.083 +/- 0.079,0.083 +/- 0.079,0.071 +/- 0.057,0.068 +/- 0.075,0.075 +/- 0.063,0.079 +/- 0.059,0.076 +/- 0.065,0.024 +/- 0.056
3,drs,-,-,0.075 +/- 0.069,0.102 +/- 0.067,0.105 +/- 0.065,0.094 +/- 0.077,0.095 +/- 0.075,0.065 +/- 0.059,0.064 +/- 0.058,0.070 +/- 0.067,0.001 +/- 0.002
4,dmls,-,-,0.078 +/- 0.070,0.083 +/- 0.079,0.083 +/- 0.079,0.086 +/- 0.073,0.087 +/- 0.066,0.090 +/- 0.072,0.107 +/- 0.092,0.088 +/- 0.073,0.016 +/- 0.016
5,xl,-,-,-,0.076 +/- 0.075,0.076 +/- 0.075,0.081 +/- 0.075,0.075 +/- 0.078,0.073 +/- 0.064,0.077 +/- 0.074,0.067 +/- 0.069,0.003 +/- 0.007
6,cf,-,-,-,0.074 +/- 0.069,0.079 +/- 0.067,0.075 +/- 0.068,0.076 +/- 0.068,0.072 +/- 0.064,0.072 +/- 0.064,0.072 +/- 0.064,0.053 +/- 0.067
7,sl_mlp,0.068 +/- 0.066,0.071 +/- 0.065,-,0.071 +/- 0.086,0.087 +/- 0.081,0.064 +/- 0.074,0.063 +/- 0.067,0.075 +/- 0.068,0.075 +/- 0.076,0.071 +/- 0.072,0.023 +/- 0.057
8,tl_mlp,0.066 +/- 0.078,0.075 +/- 0.074,-,0.098 +/- 0.090,0.081 +/- 0.081,0.087 +/- 0.077,0.086 +/- 0.087,0.078 +/- 0.052,0.088 +/- 0.074,0.065 +/- 0.061,0.010 +/- 0.029

In [18]:
df[['name', f'{avg_metric}_mse', f'{avg_metric}_r2', f'{avg_metric}_mixed', f'{avg_metric}_test']]

     name          att_mse           att_r2        att_mixed         att_test
0      sl  0.066 +/- 0.060  0.076 +/- 0.061                -  0.003 +/- 0.004
1      tl  0.074 +/- 0.069  0.077 +/- 0.067                -  0.000 +/- 0.000
2   ipsws  0.077 +/- 0.075  0.080 +/- 0.073                -  0.024 +/- 0.056
3     drs                -                -  0.075 +/- 0.069  0.001 +/- 0.002
4    dmls                -                -  0.078 +/- 0.070  0.016 +/- 0.016
5      xl                -                -                -  0.003 +/- 0.007
6      cf                -                -                -  0.053 +/- 0.067
7  sl_mlp  0.068 +/- 0.066  0.071 +/- 0.065                -  0.023 +/- 0.057
8  tl_mlp  0.066 +/- 0.078  0.075 +/- 0.074                -  0.010 +/- 0.029

In [19]:
df = show(df_all, ite_metric, 'pehe', plugin_models, rscore_base_models)
df

,name,policy_mse,policy_r2,policy_mixed,policy_sl_dt_pehe,policy_sl_lgbm_pehe,policy_tl_dt_pehe,policy_tl_lgbm_pehe,policy_rs_dt,policy_rs_lgbm,policy_rs_cb,policy_test
0,sl,0.261 +/- 0.057,0.262 +/- 0.063,-,0.297 +/- 0.060,0.297 +/- 0.060,0.242 +/- 0.059,0.247 +/- 0.056,0.246 +/- 0.048,0.211 +/- 0.037,0.217 +/- 0.045,0.158 +/- 0.034
1,tl,0.235 +/- 0.058,0.237 +/- 0.055,-,0.284 +/- 0.042,0.282 +/- 0.042,0.251 +/- 0.047,0.257 +/- 0.045,0.236 +/- 0.052,0.241 +/- 0.047,0.217 +/- 0.032,0.128 +/- 0.036
2,ipsws,0.245 +/- 0.038,0.245 +/- 0.033,-,0.296 +/- 0.060,0.297 +/- 0.060,0.241 +/- 0.065,0.229 +/- 0.046,0.271 +/- 0.048,0.248 +/- 0.058,0.251 +/- 0.046,0.158 +/- 0.038
3,drs,-,-,0.240 +/- 0.029,0.265 +/- 0.051,0.264 +/- 0.051,0.253 +/- 0.040,0.261 +/- 0.044,0.236 +/- 0.035,0.243 +/- 0.046,0.235 +/- 0.050,0.149 +/- 0.030
4,dmls,-,-,0.264 +/- 0.043,0.293 +/- 0.061,0.293 +/- 0.061,0.277 +/- 0.069,0.255 +/- 0.047,0.248 +/- 0.039,0.271 +/- 0.062,0.238 +/- 0.043,0.193 +/- 0.035
5,xl,-,-,-,0.218 +/- 0.033,0.218 +/- 0.033,0.249 +/- 0.053,0.251 +/- 0.048,0.218 +/- 0.034,0.233 +/- 0.057,0.220 +/- 0.052,0.153 +/- 0.038
6,cf,-,-,-,0.250 +/- 0.052,0.254 +/- 0.051,0.256 +/- 0.060,0.258 +/- 0.057,0.226 +/- 0.040,0.225 +/- 0.047,0.225 +/- 0.048,0.204 +/- 0.050
7,sl_mlp,0.254 +/- 0.055,0.257 +/- 0.052,-,0.277 +/- 0.082,0.273 +/- 0.093,0.255 +/- 0.040,0.251 +/- 0.045,0.238 +/- 0.052,0.251 +/- 0.042,0.242 +/- 0.036,0.162 +/- 0.029
8,tl_mlp,0.226 +/- 0.041,0.248 +/- 0.067,-,0.269 +/- 0.074,0.246 +/- 0.063,0.257 +/- 0.037,0.243 +/- 0.047,0.218 +/- 0.040,0.216 +/- 0.046,0.220 +/- 0.041,0.132 +/- 0.028

In [20]:
df[['name', f'{ite_metric}_mse', f'{ite_metric}_r2', f'{ite_metric}_mixed', f'{ite_metric}_test']]

     name       policy_mse        policy_r2     policy_mixed      policy_test
0      sl  0.261 +/- 0.057  0.262 +/- 0.063                -  0.158 +/- 0.034
1      tl  0.235 +/- 0.058  0.237 +/- 0.055                -  0.128 +/- 0.036
2   ipsws  0.245 +/- 0.038  0.245 +/- 0.033                -  0.158 +/- 0.038
3     drs                -                -  0.240 +/- 0.029  0.149 +/- 0.030
4    dmls                -                -  0.264 +/- 0.043  0.193 +/- 0.035
5      xl                -                -                -  0.153 +/- 0.038
6      cf                -                -                -  0.204 +/- 0.050
7  sl_mlp  0.254 +/- 0.055  0.257 +/- 0.052                -  0.162 +/- 0.029
8  tl_mlp  0.226 +/- 0.041  0.248 +/- 0.067                -  0.132 +/- 0.028